version: "3.7"

services:
  application:
    image: docker.io/asapdotid/php-nginx:8.1
    ports:
      - 80:80
    networks:
      - proxy
    environment:
      - PHP_POST_MAX_SIZE=100M
      - PHP_UPLOAD_MAX_FILESIZE=100M
    volumes:
      - ./www:/app

networks:
  proxy:
    name: proxy
    driver: bridge
    external: true
