version: "3.7"

services:
  application:
    image: docker.io/asapdotid/php-nginx:8.1
    expose:
      - 80
    networks:
      - proxy
    environment:
      - PHP_POST_MAX_SIZE=100M
      - PHP_UPLOAD_MAX_FILESIZE=100M
      # uncomment for laravel
      # - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=app.jogjascript.com
    volumes:
      - ./www:/app
    # proxy with traefik
    # https://github.com/asapdotid/dcc-traefik
    labels:
      - traefik.enable=true
      - traefil.docker.network=proxy
      - traefik.http.routers.portainer.entrypoints=http
      - traefik.http.routers.portainer.rule=Host(`app.jogjascript.com`)

networks:
  proxy:
    name: proxy
    driver: bridge
    external: true
